databases:
  - name: auto-placer
    databaseName: auto_placer
    user: auto_placer
    plan: free

services:
  - type: web
    name: auto-placer
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    region: singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auto-placer
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
